### ISSUE TITLE
Connection string is sometimes required

### ISSUE THREAD

**Issue by spuder** [cvent/octopus-deploy-cookbook#102]
If you use the octopus_server resource, you must provide a connection string if you wish to use the `:configure` action

```
 ================================================================================
           Error executing action `configure` on resource 'octopus_deploy_server[OctopusServer]'
           ================================================================================

           Mixlib::ShellOut::ShellCommandFailed
           ------------------------------------
           powershell_script[configure-server-OctopusServer] (C:/Users/vagrant/AppData/Local/Temp/kitchen/cache/cookbooks/octopus-deploy/resources/server.rb line 76) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
           ---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20170920-2732-b3ylnp.ps1" ----
           STDOUT:
           STDERR: ===============================================================================Missing required value for option '--storageConnectionString'.

           Octopus.Shared.Internals.Options.OptionException

       at Octopus.Shared.Internals.Options.OptionValueCollection.AssertValid(Int32 index)

       at Octopus.Shared.Internals.Options.OptionSet.<>c__DisplayClass16_0.<Add>b__0(OptionValueCollection v)

       at Octopus.Shared.Internals.Options.Option.Invoke(OptionContext c)

       at Octopus.Shared.Internals.Options.OptionSet.Parse(IEnumerable`1 arguments)

       at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions)

       at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown)

       at Octopus.Shared.Startup.OctopusProgram.Run()
```

**Comment by brentm5** [comment]
Resolved with #103
