### ISSUE TITLE
admin_user only works for LDAP

### ISSUE THREAD

**Issue by spuder** [cvent/octopus-deploy-cookbook#113]
If you define `admin_user` on a machine that isn't part of an active directory domain, and you don't specify password, you will get error `The LDAP server is unavailable`

```
 * octopus_deploy_server[OctopusServer] action configure[2017-09-21T21:26:34+00:00] WARN: Please use the package resource available in Chef Client 12.6.
       windows_package will be removed in the next major version release
       of the Windows cookbook.


           * remote_file[C:\Users\vagrant\AppData\Local\Temp\kitchen\cache/octopus-server.msi] action create
           * windows_package[Octopus Deploy Server] action install
           * powershell_script[create-instance-OctopusServer] action run (skipped due to not_if)
           * powershell_script[configure-server-OctopusServer] action run

             ================================================================================
             Error executing action `run` on resource 'powershell_script[configure-server-OctopusServer]'
             ================================================================================

             Mixlib::ShellOut::ShellCommandFailed
             ------------------------------------
             Expected process to exit with [0], but received '1'
             ---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Windows/Temp/chef-script20170921-2604-15ivxwd.ps1" ----
             STDOUT:
             STDERR: ===============================================================================The server could not be contacted.

             System.DirectoryServices.AccountManagement.PrincipalServerDownException

         at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)

         at System.DirectoryServices.AccountManagement.PrincipalContext.DoServerVerifyAndPropRetrieval()

         at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container, ContextOptions options, String userName, String password)

         at System.DirectoryServices.AccountManagement.PrincipalContext..ctor(ContextType contextType, String name, String container)

         at Octopus.Server.Extensibility.Authentication.DirectoryServices.DirectoryServices.DirectoryServicesContextProvider.GetContext(String domain)

         at Octopus.Server.Extensibility.Authentication.DirectoryServices.DirectoryServices.UserMatcher.Match(String name, CancellationToken cancellationToken)

         at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()

         at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)

         at Octopus.Server.Commands.AdminCommand.Start()

         at Octopus.Shared.Startup.AbstractCommand.Start(String[] commandLineArguments, ICommandRuntime commandRuntime, OptionSet commonOptions)

         at Octopus.Shared.Startup.ConsoleHost.Run(Action`1 start, Action shutdown)

         at Octopus.Shared.Startup.OctopusProgram.Run()



             --Inner Exception--

             The LDAP server is unavailable.

             System.DirectoryServices.Protocols.LdapException

         at System.DirectoryServices.Protocols.LdapConnection.Connect()

         at System.DirectoryServices.Protocols.LdapConnection.SendRequestHelper(DirectoryRequest request, Int32& messageID)

         at System.DirectoryServices.Protocols.LdapConnection.SendRequest(DirectoryRequest request, TimeSpan requestTimeout)

         at System.DirectoryServices.AccountManagement.PrincipalContext.ReadServerConfig(String serverName, ServerProperties& properties)

             -------------------------------------------------------------------------------
```

**Comment by spuder** [comment]
I've opened a pull request to update the documentation. 

This could also be resolved by checking if the machine is joined to a domain. Ohai can also check if a machine is joined to a domain

    if node['kernel']['cs_info']['domain_role'].to_i == 1 || node['kernel']['cs_info']['domain_role'].to_i == 3

The possible values of `domain_role`
```
StandaloneWorkstation = 0
MemberWorkstation = 1
StandaloneServer = 2
MemberServer = 3
BackupDomainController = 4
PrimaryDomainController = 5
```

**Comment by brentm5** [comment]
Yeah I ran into this before. I ended up not trying to figure out a way to fix it because our workflows usually don't call for spinning up a new cluster of OD all that often so adding the first seed user isn't needed.  Also as auth providers are added there probably needs to be a better workflow to set those up / add users
